services:
  # ====================
  # Frontend
  # ====================
  # frontend:
  #   build:
  #     context: ./Frontend
  #     dockerfile: Dockerfile.dev
  #   container_name: picados-ya-frontend
  #   ports:
  #     - ${FRONTEND_PORT}:${FRONTEND_PORT}

  # ====================
  # Base de datos
  # ====================
  mysql:
    image: mysql:8.0
    container_name: picados-ya-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS:?error}
      MYSQL_DATABASE: ${DB_DATABASE:?error}
    ports:
      - "${DB_PORT:?error}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backups/picadosya_latest.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
