services:
  # ====================
  # Frontend
  # ====================
  # frontend:
  #   build:
  #     context: ./Frontend
  #     dockerfile: Dockerfile.dev
  #   container_name: picados-ya-frontend
  #   ports:
  #     - ${FRONTEND_PORT}:${FRONTEND_PORT}

  # ====================
  # Base de datos
  # ====================
  mysql:
    image: mysql:8.0
    container_name: picados-ya-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS:?error}
      MYSQL_DATABASE: ${DB_DATABASE:?error}
    ports:
      - "${DB_PORT:?error}:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
  migrations:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
      - ./scripts/wait-for-it.sh:/wait-for-it.sh
      - .env:/.env  # Monta el script en el contenedor
    entrypoint: ["sh", "./wait-for-it.sh"]
    depends_on:
      mysql:
        condition: service_started

volumes:
  mysql_volume:
    driver: local